# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "devops" ]
  #pull_request:
  #  branches: [ "devops" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: syr-org-v1

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    #- name: Set up JDK 17
    #  uses: actions/setup-java@v3
    #  with:
    #    java-version: '17'
    #    distribution: 'corretto'
    #    cache: maven
    - name: Get Version from pom.xml
      id: get_version
      run: echo ::set-output name=VERSION::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    #- name: Build and push docker image
    #  shell: bash
    #  run: |
    #    docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }} .
    #    docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_PASSWORD }}
    #    docker push  ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}
    #    docker login -t 0 https://index.docker.io/v1/
    #    docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: docker.io
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
        # Specifies whether the given registry is ECR (auto, true or false)
        #ecr: # optional, default is auto
        # Log out from the Docker registry at the end of a job
        #logout: # optional, default is true
    - name: Build and push docker image
      shell: bash
      run:  |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }} .
        docker push  ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}
        
